### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by SunnyTeater** [CastawayLabs/cachet-monitor#116]
Hi guys,

i have cachet installed on a debian 10 (stable) system and followed the installation guide on the main side and in #86  (the default installation guide could be better)

after trying so much i just use the default config.json and only changed API key and URL

https://pastebin.com/DHUyh7cx - configuration

if i now use the command:

> $  cachet_monitor -c config.json

i get this error:

> WARN[0000] Unable to parse configuration file
> PANI[0000] Unable to start (reading config): invalid character 'a' looking for beginning of value
> panic: (*logrus.Entry) (0x7f6740,0xc42004cf50)
> 
> goroutine 1 [running]:
> panic(0x7f6740, 0xc42004cf50)
>         /usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
> github.com/Sirupsen/logrus.Entry.log(0xc42004c5f0, 0xc42000bef0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420039c00, ...)
>         /Users/m/p/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x423
> github.com/Sirupsen/logrus.(*Entry).Panic(0xc42004ce60, 0xc420039cb8, 0x1, 0x1)
>         /Users/m/p/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x124
> github.com/Sirupsen/logrus.(*Entry).Panicf(0xc42004ce60, 0x80e72a, 0x24, 0xc420039ed8, 0x1, 0x1)
>         /Users/m/p/go/src/github.com/Sirupsen/logrus/entry.go:217 +0x101
> github.com/Sirupsen/logrus.(*Logger).Panicf(0xc42004c5f0, 0x80e72a, 0x24, 0xc420039ed8, 0x1, 0x1)
>         /Users/m/p/go/src/github.com/Sirupsen/logrus/logger.go:172 +0x86
> github.com/Sirupsen/logrus.Panicf(0x80e72a, 0x24, 0xc420039ed8, 0x1, 0x1)
>         /Users/m/p/go/src/github.com/Sirupsen/logrus/exported.go:147 +0x5f
> main.main()
>         /Users/m/p/go/src/github.com/castawaylabs/cachet-monitor/cli/main.go:52 +0xd52

i think i did everything wrong, but i could not find any better documentation.
So please be gracious to me.

Thanks.

**Comment by SpeedyCraftah** [comment]
same issue

**Comment by dylie** [comment]
Found a fix for this guys??

**Comment by MatzeKitt** [comment]
You’re using a file with a `json` extension but with a `yaml` format. Use the `json` format inside your file or rename the config file to `config.yml`.
