### ISSUE TITLE
Can't create a config file.

### ISSUE THREAD

**Issue by ThomLSA** [CastawayLabs/cachet-monitor#70]
```
cachet-monitor -c /root/cachet-monitor.json                                                                                                                                                                                PANI[0000] Unable to start (reading config): Unable to open file: '/root/cachet-                                                                                                                                                             monitor.json'
panic: (*logrus.Entry) (0x7f6740,0xc420040eb0)

goroutine 1 [running]:
panic(0x7f6740, 0xc420040eb0)
        /usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
github.com/Sirupsen/logrus.Entry.log(0xc4200405f0, 0xc42000bf50, 0x0, 0x0, 0x0,                                                                                                                                                              0x0, 0x0, 0x0, 0x0, 0xc420037c00, ...)
        /Users/m/p/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x423
github.com/Sirupsen/logrus.(*Entry).Panic(0xc420040e60, 0xc420037cb8, 0x1, 0x1)
        /Users/m/p/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x124
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc420040e60, 0x80e72a, 0x24, 0xc4200                                                                                                                                                             37ed8, 0x1, 0x1)
        /Users/m/p/go/src/github.com/Sirupsen/logrus/entry.go:217 +0x101
github.com/Sirupsen/logrus.(*Logger).Panicf(0xc4200405f0, 0x80e72a, 0x24, 0xc420                                                                                                                                                             037ed8, 0x1, 0x1)
        /Users/m/p/go/src/github.com/Sirupsen/logrus/logger.go:172 +0x86
github.com/Sirupsen/logrus.Panicf(0x80e72a, 0x24, 0xc420037ed8, 0x1, 0x1)
        /Users/m/p/go/src/github.com/Sirupsen/logrus/exported.go:147 +0x5f
main.main()
        /Users/m/p/go/src/github.com/castawaylabs/cachet-monitor/cli/main.go:52                                                                                                                                                              +0xd52

```

Got this problem. 👎

**Comment by matejkramny** [comment]
No idea why it doesn't carry the panic message, but it's `Unable to start (reading config): %v`

**Comment by matejkramny** [comment]
Is the json file well formed?

**Comment by ThomLSA** [comment]
Fixed :) Was a problem in the json. 👍
